//manualtriger
name: Java Automation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify the Java version you need

      - name: Build with Maven
        run: mvn clean install -B -DskipTests # Modify this command according to your build process

      - name: Run Tests
        run: mvn test # Command to execute your Java tests

